@baseUrl = http://localhost:3002

### 1. GET All Products (req.query) ?name=undefined
GET {{baseUrl}}/products

### 2. GET Product by name (req.query) ?name=light ,manda, jedi, etc.
GET {{baseUrl}}/products?name=jedi

### 3. GET Product by ID
GET {{baseUrl}}/products/1779778641624

### 4. POST Add new Product (201)
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Sith Mask",
    "price": 2500,
    "quantity": 1
}

### 5. POST Add new Product (400)
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Droid Parts"
}

### 6. PUT Update Product
PUT {{baseUrl}}/products/1779781907849
Content-Type: application/json

{
    "price": 99999
}

### 7. DELETE Product
DELETE {{baseUrl}}/products/1779781907851